name: Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
    - run: |
        git tag ${{ inputs.tag }}
        git push origin ${{ inputs.tag }}